WINDOW_BG_COLOUR = 'MediumPurple4' # TODO: temporary colour
TEXT_FG_COLOUR = 'black'

WINDOW_INIT_WIDTH=640
WINDOW_INIT_HEIGHT=480

WINDOW_MIN_WIDTH=WINDOW_INIT_WIDTH
WINDOW_MIN_HEIGHT=WINDOW_INIT_HEIGHT